version: '3.7'

services:
  puppeteer:
    build:
      context: .
      dockerfile: docker/development/nodejs/Dockerfile
    init: true
    cap_add:
      - SYS_ADMIN
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    working_dir: /app
